name: camera_hooks
description: Flutter hooks for Camera
version: 0.0.2
repository: https://github.com/HosseinYousefi/camera_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.2+1
  flutter_hooks: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: